server:
  port: 8080
spring:
  application:
    name: "franchises"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
springdoc:
  swagger-ui:
    path: /swagger
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  region: us-east-1
  dynamodb:
    endpoint: "http://localhost:4566"

app:
  dynamo:
    core-table: core_table
